apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  labels:
    app: two-tier-app
spec:
  replicas: 3  # number of pods
  selector:
    matchLabels:
      app: two-tier-app # this will select only these lebel for pods creation.
  template: # pods creation template 
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: devesh121/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "10.99.162.5"          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
